services:
  - type: web
    name: doctor-patient-appointment-api
    env: node
    rootDir: project/doctor_patient_appointment_booking/backend
    buildCommand: npm install && cd ../realFrontEnd && npm install && npm run build
    startCommand: npm start
    healthCheckPath: /